config/routes.rb
Rails.application.routes.draw do
  #Topページへのルート
  root to: 'static_pages#home'
  
  #新規登録へのルート
  get 'signup', to: 'users#new'

  #ログイン・ログアウトのルート
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #フォロー一覧、フォロワー一覧のルート
  get    'show_following_user/:id', to: 'users#show_following_user', as: 'show_following_user'
  get    'show_follower_user/:id',  to: 'users#show_follower_user', as: 'show_follower_user'
  
  #お気に入り一覧
  get    'show_favorite/:id', to: 'users#show_favorite', as: 'show_favorite'
  
  #お気に入りの登録
  post   'favorite/:id', to: 'favorites#create', as: 'favorites'

  resources :users
  resources :microposts do
    member do
      get 'retweet'
     end
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  #セーブする前にメールアドレスを小文字に変換する
  before_save {self.email = self.email.downcase}

  #名前の入力のルール
  validates :name, presence: true, length: {maximum: 50}
  
  #メールアドレスの入力ルール
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
              format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
              
  #プロフィールの入力ルール(未入力でもOK)
  validates :profile, presence: true, length: {maximum: 160}, if: "profile.present?"
  
  #地域の入力のルール(未入力でもOK)
  validates :area, presence: true, length: {maximum: 50}, if: "area.present?"
  
  #生年月日の入力(未入力でもOK)
  validates :birthday, presence: true, length: {minimum: 8, maximum: 8}, numericality: {only_integer: true}, if: "birthday.present?"
 
  #パスワードの暗号化をする
  has_secure_password
  
  #一人のユーザーにつき複数の投稿を保持できるようにする
  has_many :microposts
  
  #一人のユーザーがフォローしているrelationshipの集まり
  has_many :following_relationships, class_name: "Relationship",
              foreign_key: "follower_id", dependent: :destroy
              
  
  #一人のユーザーがフォローしている人の集まり
  has_many :following_users, through: :following_relationships, source: :followed
  
  #一人のユーザーをフォローしているrelationshipの集まり
  has_many :follower_relationships, class_name: "Relationship",
              foreign_key: "followed_id", dependent: :destroy
  
  #一人のユーザーをフォローしている人の集まり
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  #
  has_many :favorites, foreign_key: "user_id", dependent: :destroy
  
  #
  has_many :favorites_microposts, class_name: "Micropost", through: :favorites, source: :micropost
                
 
  #他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end
  
  #フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end
  
  #あるユーザーをフォローしているかどうか
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  #投稿をお気に入りにする
  def favolite(micropost)
    favorites.find_or_create_by(micropost_id: micropost)
  end

  #投稿をお気に入りを取り消す
  def unfavolite(micropost)
    favorite = favorites.find_by(micropost_id: micropost)
    favorite.destroy if favorite
  end
  
  #投稿をお気に入りしているかどうか
  def favoliting?(micropost)
    Favorite.find_by(micropost_id: micropost)
  end

  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,
    only: [:show, :edit, :update, :show_following_user, :show_follower_user, :show_favorite]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Sample App!"
      redirect_to user_path(@user[:id])
    else
      render 'new'
    end
  end
  
  def show
    @microposts = @user.microposts.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def edit
    if @user.id != current_user.id
      redirect_to root_path
    end
  end
  
  def update
    if @user.id != current_user.id
      redirect_to root_path
    else
      if @user.update(user_params)
        flash[:success] = "Profile changed"
        redirect_to user_path(@user[:id])
      else
        render 'edit'
      end
    end 
  end
  
  def show_following_user
    @following_users = @user.following_users.order(created_at: :desc).page(params[:page]).per(15)
  end

  def show_follower_user
    @follower_users = @user.follower_users.order(created_at: :desc).page(params[:page]).per(15)
  end

  def show_favorite
    @favoriting_microposts = @user.favorites_microposts.order(created_at: :desc).page(params[:page]).per(10)
  end
    
  #-----------------------
  #ここからprivateメソッド
  #-----------------------
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :area, :birthday)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?=#[size}"
    image_tag(gravatar_url, alt: user.name, class: "gravater")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div>
    <%= hidden_field_tag :followed_id, @user.id %>
  </div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_favorite.html.erb
<%= link_to "", favorites_path(micropost), remote: true, method: :post, class: 'glyphicon glyphicon-star-empty' %>

app/views/users/_follow_favorite_form.html.erb
<% if current_user.favoliting?(micropost) %>
  <%= render 'users/unfollow_favorite', micropost: micropost %>
<% else %>
  <%= render 'users/follow_favorite', micropost: micropost %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form" %>
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
          html: {method: :delete}, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_unfollow_favorite.html.erb
<%= link_to "", favorite_path(micropost), remote: true, method: :delete, class: 'glyphicon glyphicon-star' %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<!-- プロフィールの更新入力 -->
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <!-- 変更後のメールアドレスの入力 -->
      <%= f.label :email, "Email"%><br>
      <%= f.text_field :email, class: "form-control", placeholder: "メールアドレスを入力してください。" %>
    
      <!-- 自己紹介文の記載self‐introduction -->
      <%= f.label :profile, "Self-introduction" %>
      <%= f.text_area :profile, class: "form-control", placeholder: "自己紹介文を入力してください(160文字以内)。" %>

      <!-- 地域を入力 -->
      <%= f.label :area, "Area" %>
      <%= f.text_field :area, class: "form-control", placeholder: "地域を入力してください。" %>
      
      <!-- 生年月日を入力 -->
      <%= f.label :birthday, "Birthday" %>
      <%= f.text_field :birthday, class: "form-control", placeholder: "生年月日を入力してください。例）2017年1月1日の場合：20170101" %>
      
      <!-- 更新ボタン -->
      <%= f.submit "Update profile", class: "btn btn-large btn-primary" %>
     <% end %>
  </div>  
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <!-- エラーの際の表示 -->
      <%= render 'shared/error_messages', object: f.object %>
      
      <!-- 名前の入力 -->
      <%= f.label :name %>
      <%= f.text_field :name, class: "form_control" %>
      
      
      <!-- メールアドレスの入力 -->
      <%= f.label :email %>
      <%= f.text_field :email, class: "form_control" %>
      
      <!-- パスワードの入力 -->
      <%= f.label :password %>
      <%= f.password_field :password, class: "form_control" %>

      <!-- パスワードの確認用の再入力 -->
      <%=f.label :password_confirmation, "Confirmation" %>
      <%=f.password_field :password_confirmation, class: "form_control" %>
      
      <!-- 送信ボタン -->
      <%=f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!-- ユーザー名と画像を表示 -->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for(@user) %>
      <h1>
        <%= @user.name %>  
      </h1>
      <span>
        <%= link_to pluralize(@user.microposts.count, "micropost"), user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.following_users.count, "follow"), show_following_user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.follower_users.count, "follower"), show_follower_user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.favorites.count, "favorite"), show_favorite_path(@user) %>
      </span>
    </section>

    <section class="profile">
      <!-- 自己紹介文の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">自己紹介</div>
        <div class="panel-body"><%= simple_format(@user.profile) %></div>
      </div>
      
      <!-- 地域の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">地域</div>
        <div class="panel-body"><%= @user.area %></div>
      </div>    
      
      <!-- 生年月日の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">生年月日</div>
        <div class="panel-body">
          <%= @user.birthday.to_s[0, 4] %>年
          <%= @user.birthday.to_s[4, 2] %>月
          <%= @user.birthday.to_s[6, 2] %>日
        </div>
      </div>    
      
      <!-- 最終更新日の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">最終更新日</div>
        <div class="panel-body"><%= @user.updated_at %></div>
      </div>
    </section>
  </aside>

  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <%= page_entries_info @microposts %>
      <h3>Microposts(<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>  
      </ol>
      <%= paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_favorite.html.erb
<!-- ユーザー名と画像を表示 -->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for(@user) %>
      <h1>
        <%= @user.name %>
      </h1>
      <span>
        <%= link_to pluralize(@user.microposts.count, "micropost"), user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.following_users.count, "follow"), show_following_user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.follower_users.count, "follower"), show_follower_user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.favorites.count, "favorite"), show_favorite_path(@user) %>
      </span>
    </section>

    <section class="profile">
      <!-- 自己紹介文の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">自己紹介</div>
        <div class="panel-body"><%= simple_format(@user.profile) %></div>
      </div>
      
      <!-- 地域の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">地域</div>
        <div class="panel-body"><%= @user.area %></div>
      </div>    
      
      <!-- 生年月日の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">生年月日</div>
        <div class="panel-body">
          <%= @user.birthday.to_s[0, 4] %>年
          <%= @user.birthday.to_s[4, 2] %>月
          <%= @user.birthday.to_s[6, 2] %>日
        </div>
      </div>    
      
      <!-- 最終更新日の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">最終更新日</div>
        <div class="panel-body"><%= @user.updated_at %></div>
      </div>
    </section>
  </aside>

  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.favorites_microposts.any? %>
      <%= page_entries_info @favoriting_microposts %>
      <h3>Favorites(<%= @favoriting_microposts.count %>)</h3>
      <ol class="microposts">
        <% @favoriting_microposts.each do |favoriting_micropost| %>
          <%= render favoriting_micropost %> 
        <% end %>
      </ol>
      <%= paginate @favoriting_microposts %>
    <% end %>
  </div>
</div>

        

app/views/users/show_follower_user.html.erb
<!-- ユーザー名と画像を表示 -->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for(@user) %>
      <h1>
        <%= @user.name %>  
      </h1>
      <span>
        <%= link_to pluralize(@user.microposts.count, "micropost"), user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.following_users.count, "follow"), show_following_user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.follower_users.count, "follower"), show_follower_user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.favorites.count, "favorite"), show_favorite_path(@user) %>
      </span>
    </section>

    <section class="profile">
      <!-- 自己紹介文の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">自己紹介</div>
        <div class="panel-body"><%= simple_format(@user.profile) %></div>
      </div>
      
      <!-- 地域の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">地域</div>
        <div class="panel-body"><%= @user.area %></div>
      </div>    
      
      <!-- 生年月日の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">生年月日</div>
        <div class="panel-body">
          <%= @user.birthday.to_s[0, 4] %>年
          <%= @user.birthday.to_s[4, 2] %>月
          <%= @user.birthday.to_s[6, 2] %>日
        </div>
      </div>    
      
      <!-- 最終更新日の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">最終更新日</div>
        <div class="panel-body"><%= @user.updated_at %></div>
      </div>
    </section>
  </aside>

  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.follower_users.any? %>
      <%= page_entries_info @follower_users %>
      <h3>Followers(<%= @user.follower_users.count %>)</h3>
      <ol class="following_follower">
        <div class="row">
          <% @follower_users.each do |follower_user| %>
            <div class="col-md-4">
              <%= render partial: 'relationships/follower_users', locals: {follower_user: follower_user} %>
              <br>
              <%= follower_user.profile %>
            </div>
          <% end %>
        </div>
      </ol>
      <%= paginate @follower_users %>
    <% end %>
  </div>
</div>

app/views/users/show_following_user.html.erb
<!-- ユーザー名と画像を表示 -->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for(@user) %>
      <h1>
        <%= @user.name %>  
      </h1>
      <span>
        <%= link_to pluralize(@user.microposts.count, "micropost"), user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.following_users.count, "follow"), show_following_user_path(@user) %>
      </span>
      <span>
        <%= link_to pluralize(@user.follower_users.count, "follower"), show_follower_user_path(@user) %>
      </span>
       <span>
        <%= link_to pluralize(@user.favorites.count, "favorite"), show_favorite_path(@user) %>
      </span>
    </section>

    <section class="profile">
      <!-- 自己紹介文の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">自己紹介</div>
        <div class="panel-body"><%= simple_format(@user.profile) %></div>
      </div>
      
      <!-- 地域の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">地域</div>
        <div class="panel-body"><%= @user.area %></div>
      </div>    
      
      <!-- 生年月日の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">生年月日</div>
        <div class="panel-body">
          <%= @user.birthday.to_s[0, 4] %>年
          <%= @user.birthday.to_s[4, 2] %>月
          <%= @user.birthday.to_s[6, 2] %>日
        </div>
      </div>    
      
      <!-- 最終更新日の表示 -->
      <div class="panel panel-primary">
        <div class="panel-heading">最終更新日</div>
        <div class="panel-body"><%= @user.updated_at %></div>
      </div>
    </section>
  </aside>

  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.following_users.any? %>
      <%= page_entries_info @following_users %>
      <h3>Follows(<%= @user.following_users.count %>)</h3>
      <ol class="following_follower">
        <div class="row">
          <% @following_users.each do |following_user| %>
            <div class="col-md-4">
              <%= render partial: 'relationships/following_users', locals: {following_user: following_user} %>
              <br>
              <%= following_user.profile %>
            </div>
          <% end %>
        </div>
      </ol>
      <%= paginate @following_users %>
    <% end %>
  </div>
</div>