config/routes.rb
Rails.application.routes.draw do
  #Topページへのルート
  root to: 'static_pages#home'
  
  #新規登録へのルート
  get 'signup', to: 'users#new'

  #ログイン・ログアウトのルート
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  #フォロー一覧、フォロワー一覧のルート
  get    'show_following_user/:id', to: 'users#show_following_user', as: 'show_following_user'
  get    'show_follower_user/:id',  to: 'users#show_follower_user', as: 'show_follower_user'
  
  #お気に入り一覧
  get    'show_favorite/:id', to: 'users#show_favorite', as: 'show_favorite'
  
  #お気に入りの登録
  post   'favorite/:id', to: 'favorites#create', as: 'favorites'

  resources :users
  resources :microposts do
    member do
      get 'retweet'
     end
  end
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:destroy]
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  #ユーザーIDの入力規則
  validates :user_id, presence: true
  
  #投稿内容の入力規則
  validates :content, presence: true, length: {maximum: 140}
  
  #複数の投稿は特定の1人のユーザーのものである
  belongs_to :user
  
  #
  has_many :favorites, foreign_key: "micropost_id", dependent: :destroy
  
  #
  has_many :favorites_userss, class_name: "User", through: :favorites,  source: :micropost
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created"
      redirect_to root_url
    else
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  def retweet
    origin_tweet = Micropost.find(params[:id])
    origin_user  = User.find(Micropost.find(params[:id]).user_id)
    @micropost = current_user.microposts.build(origin_id: origin_tweet.id,
                    origin_user_id: origin_user.id, origin_name: origin_user.name, content: origin_tweet.content)
    if @micropost.save
      flash[:success] = "Retweet"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
  
  
  #----------------------------
  #ここからプライベートメソッド
  private
  
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <div class="micropost_content">
    <div class="user">
      <%= link_to micropost.user.name, micropost.user, class: "micropost_user_name"%>
      <span class="micropost_timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
      </span>
      <% if current_user == micropost.user %>
        [<%= link_to "delete", micropost, method: :delete, data: {confirm: "You sure?"}, class: "micropost_delete" %>]
      <% end %>
    </div>
    <div class="content">
      <% if micropost.origin_id != nil %>
       <span style="color: #d3d3d3"><%= micropost.user.name %>さんがリツイート</span><br>
       <%= link_to micropost.origin_name, user_path(micropost.origin_user_id)%><br>
      <% end %>
      <%= simple_format(micropost.content) %>
    </div>
    <div>
      <%= link_to "Retweet", retweet_micropost_path(micropost), class: "retweet btn btn-primary btn-sm" %>
      <span id="follow_favorite_micropost-<%= micropost.id %>">
        <%= render 'users/follow_favorite_form', micropost: micropost.id %>
      </span>
    </div>
  </div>
</li>